version: '2'

services:

  owncloud:
    image: owncloud:9
    restart: always
    ports:
      - 80:80
    volumes:
      - /mnt/data/files/admin/files
    environment:
      - ADMIN_USERNAME=admin
      - ADMIN_PASSWORD=admin
